name: github-game2048-ci
on: [workflow_dispatch]

env:
  maven_package_cache: ".m2/repository/"
  MAVEN_OPTS: "-Dmaven.repo.local=./$maven_package_cache"

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn compile
      - uses: actions/upload-artifact@v2
        with:
          name: game2048compiled
          path: ./target/*
  test:
    runs-on: self-hosted
    needs: build

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn test
  package:
      runs-on: self-hosted
      needs: build
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v2
          with:
            java-version: '11'
            distribution: 'adopt'
        - run: mvn package
        - uses: actions/upload-artifact@v2
          with:
            name: game2048packaged
            path: ./target/*.war
  deploy:
    runs-on: self-hosted
    needs:
      - package
    environment:
      name: Test Env
      url: http://localhost:8081/game2048
    steps:
      - name: Deploy Webapp
        run: cp -f ./target/*.war /usr/local/tomcat/webapps
